pipeline {
    agent {
        docker {
            image 'node:lts-buster-slim'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                // Pull the Node Docker image
                script {
                    docker.image('node:lts-buster-slim').pull()
                }
            }
        }
        
        stage('Run Docker Container') {
            steps {
                // Run the Node Docker container
                script {
                    docker.container('my-node-app') {
                        // Inside the container, clone or copy your Node.js and React application
                        // Replace the following command with your actual build command
                        sh 'npm install && npm run build'
                    }
                }
            }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
